name: ci-casper-js-sdk

on:
  push:
    branches:
      - "dev"
      - "feat-*"
      - "release-*"
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - "dev"
      - "feat-*"
      - "release-*"
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b #v3.0.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@5b949b50c3461bbcd5a540b150c368278160234a #v3.4.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm install

      - name: Audits
        run: npm audit

      - name: Lints
        run: npm run lint:ci

      - name: Test
        run: npm test

      - name: Get Latest Casper-Node Tag Version
        run: |
          echo "CASPER_TAG_VERSION=$(curl -s ${{ env.GH_API_URL }} | jq -r '.[].name' | grep 'v*' | sort -r | head -n1)" >> $GITHUB_ENV
        env:
          GH_API_URL: 'https://api.github.com/repos/casper-network/casper-node/tags'

      - name: Test RPC - Casper Node - ${{ env.CASPER_TAG_VERSION }}
        run: ./ci/setup.sh branch=${{env.CASPER_TAG_VERSION }} && npm run test:rpc
        env:
          FAUCET_PRIV_KEY: 'MC4CAQAwBQYDK2VwBCIEIH1yvW0YCDqi6tu7p/2ZXeBNMzozkfw4oWtcPNSmwl1U' #ci/test-assets/secret-key.pem
          NODE_URL: 'http://localhost:7777/rpc'
          NETWORK_NAME: 'casper-example'
          RUST_LOG: 'INFO'

      - name: Test - RPC - Casper Node - DEV
        run: ./ci/setup.sh && npm run test:rpc
        env:
          FAUCET_PRIV_KEY: 'MC4CAQAwBQYDK2VwBCIEIH1yvW0YCDqi6tu7p/2ZXeBNMzozkfw4oWtcPNSmwl1U' #ci/test-assets/secret-key.pem
          NODE_URL: 'http://localhost:7777/rpc'
          NETWORK_NAME: 'casper-example'
          RUST_LOG: 'INFO'

      - name: Docs
        run: npm run docs
