---
name: nightly-scheduled-test

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # runs every day at midnight
    - cron: "0 0 * * *"

jobs:
  nightly-make-test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b #v3.0.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@5b949b50c3461bbcd5a540b150c368278160234a #v3.4.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm install

      - name: Test
        run: npm test

      - name: Slack Notification
        uses: ravsamhq/notify-slack-action@4ed28566c2bdcdaee6dca2b46b9666d01b4ed8a4 #v1.10.0
        if: always()
        with:
          status: ${{ job.status }}
          notification_title: "*{repo}*"
          message_format: "{emoji} *{workflow}* *{status_message}* in <{repo_url}|{repo}@{branch}> on <{commit_url}|{commit_sha}>"
          footer: "<{run_url}|View Run>"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
