# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: publish-casper-client-sdk

on:
  release:
    types: [created]

jobs:
  publish:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: "public"
        check-version: true
    - name: Get latest release version number
      id: get_version
      uses: battila7/get-version-action@v2
    - run: npm run build:umd
    - run: mv dist/bundle.umd.js dist/casper-client-sdk.umd.${{ steps.get_version.outputs.version }}.js
    - uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: dist/casper-client-sdk.umd.${{ steps.get_version.outputs.version }}.js
        allow_override: true
